# Aliases for file operations.
alias s='rapid status'
alias qa='nocorrect rapid stage'
alias qn='nocorrect rapid track'
alias qap='nocorrect rapid stage --patch'
alias qd='nocorrect rapid diff'
alias qdc='nocorrect rapid diff --staged'
alias qc='nocorrect rapid drop'
alias qu='nocorrect rapid unstage'
alias qrm='nocorrect rapid remove'

alias qa='rapid stage'
alias qn='rapid track'
alias qap='rapid stage --patch'
alias qd='rapid diff'
alias qdc='rapid diff --staged'
alias qc='rapid drop'
alias qu='rapid unstage'
alias qrm='rapid remove'

# Aliases for branch operations.
alias qb='nocorrect rapid branch'
alias qco='nocorrect rapid checkout'
alias qm='nocorrect rapid merge'
alias qr='nocorrect rapid rebase'
